server:
  port: 8000

#token:
#  expiration_time: 3600
#  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJmb28iOiJiYXIiLCJpYXQiOjE0OTg1ODY1ODAsImV4cCI6MTQ5OTE5MTM4MH0YMSZ1PmRsjxyrtkLADayLJ99OEz0BzgpFZmeVXSRE8

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: gateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: auth-service  # 로그인
          uri: http://10.96.100.34:9000
          predicates:
            - Path=/auth/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service  # 회원가입
          uri: http://10.96.100.34:9000
          predicates:
            - Path=/auth/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service  # 로그아웃
          uri: http://10.96.100.34:9000
          predicates:
            - Path=/auth/logout
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service  # GET으로 시작하는 페이지는 인증 헤더 필요
          uri: http://10.96.100.34:9000
          predicates:
            - Path=/user/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            # - AuthorizationHeaderFilter   # AuthorizationHeader 검증

        - id: parse-service
          uri: lb://AMD-Backend-parse
          predicates:
            - Path=/parse/**

        - id: auth-service
          #uri: lb://AMD-Backend-Auth
          uri: http://10.96.100.34:9000
          predicates:
            - Path=/auth/actuator/**
            - Method=GET, POST
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}



token:
  expiration_time: 3600
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJmb28iOiJiYXIiLCJpYXQiOjE0OTg1ODY1ODAsImV4cCI6MTQ5OTE5MTM4MH0YMSZ1PmRsjxyrtkLADayLJ99OEz0BzgpFZmeVXSRE8

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
